# https://github.com/camunda-community-hub/spring-zeebe#configuring-camunda-platform-8-saas-connection
# https://github.com/camunda-community-hub/spring-zeebe#additional-configuration-options

camunda:
  client:
    mode: saas
    auth:
      client-id: XXX
      client-secret: XXX
    cluster-id: XXX
    region: bru-2
              
# go to http://localhost:8084/applications/ and create application of type M2M with read/write access to Operate & Tasklist
identity.clientId: pouet
identity.clientSecret: CSf4Jqwcmw6HsEocpslOvVPjZ4t8DUoP
keycloakUrl: http://localhost:18080
tasklistUrl: http://localhost:8082/
operateUrl: http://localhost:8081/

# this is to allow react application launched separately to access the WS
websocket:
  allowedOrigin: "*"

springdoc.swagger-ui.path: /swagger-ui.html

spring:
  servlet.multipart:
    max-file-size: 10MB
    max-request-size: 30MB

  security.oauth2:
    enabled: false

server:
  port: 8081
  error:
    whitelabel:
      enabled: false
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1048576

logging:
  level:
    root: INFO
